from tkinter import *
root = Tk()
name = Label(root, text="Name:")
nam_e = Entry(root, bd=1)
product = Label(root, text="Products:")
prd = Entry(root, bd=1)
quantity = Label(root, text="Quantity:")
qnt = Entry(root, bd=1)
btn = Button(root, text="Add Items")
lb = Listbox(root,height=5, width=30)
name.grid(row=0, column=0)
product.grid(row=1, column=0)
quantity.grid(row=2, column=0)
nam_e.grid(row=0, column=1)
prd.grid(row=1, column=1)
qnt.grid(row=2, column=1)
btn2 = Button(root, text="Clear Items")
btn3 = Button(root, text="Total")
lb.grid(row=4, column=1)
btn.grid(row=3, column=1)
btn2.grid(row=5,column=1)
btn3.grid(row=5, column=2)
root.mainloop()